# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GITHUB_NAME}"
  - git config --global user.email "${GITHUB_EMAIL}"
  - echo "machine github.com login ${GITHUB_NAME} password ${GITHUB_TOKEN}" > ~/.netrc
  - cd website && yarn install && GIT_USER="${GITHUB_NAME}" yarn run publish-gh-pages